services:
  composition:
    container_name: composition
    build:
      context: ./composition/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  scoring:
    container_name: scoring
    build:
      context: ./scoring/
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
  decision:
    container_name: scoring
    build:
      context: ./decision/
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
