services:
  composition:
    container_name: composition
    build:
      context: ./composition/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - scoring
      - decision
    networks:
      mai-system-design:
    environment:
      grpc.client.scoring.address: static://scoring:9091
      grpc.client.decision.address: static://decision:9092
      composition.threshold: 3.0

  scoring:
    container_name: scoring
    build:
      context: ./scoring/
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      mai-system-design:

  decision:
    container_name: decision
    build:
      context: ./decision/
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    networks:
      mai-system-design:

networks:
  mai-system-design:
    driver: 'bridge'
    ipam:
      config:
        - subnet: 172.15.15.0/24
